### ISSUE TITLE
Octave compatible?

### ISSUE THREAD

**Issue by stefano2734** [ggwadera/cfd-matlab-problems#1]
Compatible to free matlab clone octave?
No license is needed for octave.

If yes, please extend your info.
if unknown, untested with octave is also nice.
if no, it is also ok. Some commands are not compatible in octave.

**Comment by ggwadera** [comment]
Hi!

This was tested only on Matlab, I cannot guarantee that it will work on Octave.

I added this info to the project's README.

Thanks 🙂
